all: bush Max sum Strcat Maxlength

bush: bush.c
	gcc bush.c -o bush

Max: Max.c
	gcc Max.c -o Max

sum: sum.c
	gcc sum.c -o sum

Strcat: Strcat.c
	gcc Strcat.c -o Strcat

Maxlength: Maxlength.c
	gcc Maxlength.c -o Maxlength

clean:
	rm -rf *.o bush Max sum Strcat Maxlength