all: main Max sum Strcat Maxlength

main: main.c
	gcc main.c -o main

Max: Max.c
	gcc Max.c -o Max

sum: sum.c
	gcc sum.c -o sum

Strcat: Strcat.c
	gcc Strcat.c -o Strcat

Maxlength: Maxlength.c
	gcc Maxlength.c -o Maxlength

clean:
	rm -rf *.o main Max sum Strcat Maxlength